export const menuItems = [
  {
    lable: "Home",
    href: "/",
  },
  {
    lable: "Massages",
    href: "/massages",
  },
  {
    lable: "About Us",
    href: "/about Us",
  },
  {
    lable: "Jobs",
    href: "/jobs",
  },
  {
    lable: "Community",
    href: "/community",
  },
];
export const categories1 = [
  { categorie: "Full-time" },
  {
    categorie: "Part-time",
  },
  ,
  {
    categorie: "Intership",
  },
  ,
  {
    categorie: "Project work",
  },
  {
    categorie: "Volunteering",
  },
];

export const carts = [
  {
    title: "UX Researcher",
    price: "7,800",
    company: "Motorolla",
    country: "Houston.TX",
    srclogo: "/motorola1.png",
    date: "5 September",
    applicants: "159 applicants",
    workSchedule: "full-time",
    employmentType: "full day",
    workStyle: "Hyrbid",
    experience: "4-6 years",
    bg: "bg-purple-200",
    srcheart: "/heart.png",
  },
  {
    title: "Find your",
    title1:"dream job",
    desc:"Get hired faster with  ",
    desc1:"premium perks! Boost",
    desc2:"your visibility!",
    price: "",
    company: "",
    country: "",
    srclogo: "",
    date: "",
    applicants: "",
    workSchedule: "",
    employmentType: "",
    workStyle: "",
    experience: "",
    bg: " bg-gradient-to-br from-[#3a0a44] from-[10%] via-[#e23e6f] via-[#9d7fd4] via-[#d172ce] via-[#f72397] to-[#3f0c44] ",
    srcheart: "",
  },
  {
    title: "Lead UX Researcher",
    price: "6,000",
    company: "PayPal",
    country: "Los-Angeles, CA",
    srclogo: "/paypal1.png",
    date: "3 September",
    applicants: "179 applicants",
    workSchedule: "Project work",
    employmentType: "full day",
    workStyle: "Office",
    experience: "8+ years",
    bg: "bg-blue-200",
    srcheart: "/heart1.png",
  },
  {
    title: "Middle UI Designer",
    price: "5,250",
    company: "Microsoft",
     country: "Redmond, WA",
    srclogo: "/microsoft1.png",
    date: "2 September",
    applicants: "196 applicants",
    workSchedule: "Full-time",
    employmentType: "full day",
    workStyle: "Office",
    experience: "4-6 years",
    bg: "bg-green-300",
    srcheart: "/heart.png",
  },
  {
    title: "interface designer ",
    price: "3,700",
    company: "Netflix",
    country: "Son-Francisco, CA",
    srclogo: "/netflix1.png",
    date: "29 August",
    applicants: "115 applicants",
    workSchedule: "part-time",
    employmentType: "full day",
    workStyle: "Office",
    experience: "4-6 years",
    bg: "bg-red-300",
    srcheart: "/heart1.png",
  },
  {
    title: "Art Director ",
    price: "9,500",
    company: "x Crop",
    country: "Houston,TX",
    srclogo: "/x.png",
    date: "28 August",
    applicants: "159 applicants",
    workSchedule: "Full-time",
    employmentType: "full day",
    workStyle: "Hybrid",
    experience: "7-10 years",
    bg: "bg-gray-200",
    srcheart: "/heart.png",
  },
  {
    title: "Senior Product Designer",
    price: "11,000",
    company: "Motorolla",
    country: "Austin, TX",
    srclogo: "/motorola1.png",
    date: "1 October",
    applicants: "74 applicants",
    workSchedule: "Full-time",
    employmentType: "Full day",
    workStyle: "Hybrid",
    experience: "6+ years",
    bg: "bg-yellow-100",
    srcheart: "/heart1.png",
  },
  {
    title: "Junior UX Designer",
    price: "3,200",
    company: "PayPal",
    country: "San Diego, CA",
    srclogo: "/paypal1.png",
    date: "30 September",
    applicants: "42 applicants",
    workSchedule: "Part-time",
    employmentType: "Flexible schedule",
    workStyle: "Remote",
    experience: "1-2 years",
    bg: "bg-indigo-100",
    srcheart: "/heart.png",
  },
  {
    title: "Lead Product Manager",
    price: "13,500",
    company: "Microsoft",
    country: "Redmond, WA",
    srclogo: "/microsoft1.png",
    date: "15 September",
    applicants: "220 applicants",
    workSchedule: "Full-time",
    employmentType: "Full day",
    workStyle: "Office",
    experience: "8+ years",
    bg: "bg-blue-100",
    srcheart: "/heart1.png",
  },
  {
    title: "Visual Designer",
    price: "4,400",
    company: "Netflix",
    country: "San Jose, CA",
    srclogo: "/netflix1.png",
    date: "10 September",
    applicants: "86 applicants",
    workSchedule: "Project work",
    employmentType: "Shift work",
    workStyle: "Office",
    experience: "3-4 years",
    bg: "bg-red-100",
    srcheart: "/heart.png",
  },
  {
    title: "Interaction Designer",
    price: "5,900",
    company: "Motorolla",
    country: "Dallas, TX",
    srclogo: "/motorola1.png",
    date: "18 September",
    applicants: "102 applicants",
    workSchedule: "Full-time",
    employmentType: "Full day",
    workStyle: "Hybrid",
    experience: "4-6 years",
    bg: "bg-purple-100",
    srcheart: "/heart1.png",
  },
  {
    title: "UX Writer",
    price: "3,800",
    company: "PayPal",
    country: "Los Angeles, CA",
    srclogo: "/paypal1.png",
    date: "5 October",
    applicants: "28 applicants",
    workSchedule: "Part-time",
    employmentType: "Flexible schedule",
    workStyle: "Remote",
    experience: "2-3 years",
    bg: "bg-green-100",
    srcheart: "/heart.png",
  },
  {
    title: "Design Systems Engineer",
    price: "10,500",
    company: "Microsoft",
    country: "Bellevue, WA",
    srclogo: "/microsoft1.png",
    date: "20 September",
    applicants: "64 applicants",
    workSchedule: "Full-time",
    employmentType: "Full day",
    workStyle: "Office",
    experience: "6-8 years",
    bg: "bg-blue-50",
    srcheart: "/heart1.png",
  },
  {
    title: "Motion Designer",
    price: "4,900",
    company: "Netflix",
    country: "San Francisco, CA",
    srclogo: "/netflix1.png",
    date: "22 September",
    applicants: "38 applicants",
    workSchedule: "Project work",
    employmentType: "Distant work",
    workStyle: "Remote",
    experience: "3-5 years",
    bg: "bg-red-50",
    srcheart: "/heart.png",
  },
  {
    title: "Senior Art Director",
    price: "12,000",
    company: "x Crop",
    country: "Houston, TX",
    srclogo: "/x.png",
    date: "12 September",
    applicants: "190 applicants",
    workSchedule: "Full-time",
    employmentType: "Full day",
    workStyle: "Hybrid",
    experience: "9+ years",
    bg: "bg-gray-100",
    srcheart: "/heart1.png",
  },
  {
    title: "Product Design Intern",
    price: "2,200",
    company: "Motorolla",
    country: "Houston, TX",
    srclogo: "/motorola1.png",
    date: "1 August",
    applicants: "320 applicants",
    workSchedule: "Intership",
    employmentType: "Flexible schedule",
    workStyle: "Office",
    experience: "0-1 years",
    bg: "bg-yellow-50",
    srcheart: "/heart.png",
  },
  {
    title: "Senior Visual Designer",
    price: "7,200",
    company: "PayPal",
    country: "Irvine, CA",
    srclogo: "/paypal1.png",
    date: "2 July",
    applicants: "88 applicants",
    workSchedule: "Full-time",
    employmentType: "Full day",
    workStyle: "Office",
    experience: "5-7 years",
    bg: "bg-indigo-50",
    srcheart: "/heart1.png",
  },
  {
    title: "UX Strategist",
    price: "9,000",
    company: "Microsoft",
    country: "Seattle, WA",
    srclogo: "/microsoft1.png",
    date: "8 June",
    applicants: "47 applicants",
    workSchedule: "Full-time",
    employmentType: "Full day",
    workStyle: "Hybrid",
    experience: "7+ years",
    bg: "bg-blue-200",
    srcheart: "/heart.png",
  },
  {
    title: "Senior Motion Designer",
    price: "6,400",
    company: "Netflix",
    country: "Oakland, CA",
    srclogo: "/netflix1.png",
    date: "11 May",
    applicants: "53 applicants",
    workSchedule: "Project work",
    employmentType: "Shift work",
    workStyle: "Remote",
    experience: "5+ years",
    bg: "bg-red-200",
    srcheart: "/heart1.png",
  },
  {
    title: "Creative Lead",
    price: "14,000",
    company: "x Crop",
    country: "Austin, TX",
    srclogo: "/x.png",
    date: "3 April",
    applicants: "210 applicants",
    workSchedule: "Full-time",
    employmentType: "Full day",
    workStyle: "Office",
    experience: "10+ years",
    bg: "bg-gray-300",
    srcheart: "/heart.png",
  },
];

export const categories2 = [
  { categorie: "Full day" },
  {
    categorie: "Flexible schedule",
  },
  ,
  {
    categorie: "Shift work",
  },
  ,
  {
    categorie: "Distant work",
  },
];
export const categories3 = [
  { categorie: "Office" },
  {
    categorie: "Hybrid",
  },
  ,
  {
    categorie: "Remote",
  },
];
